name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev libxkbcommon-x11-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: cargo bundle
        uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release --all-features